### ISSUE TITLE
WerASagtMussAuchDSagen - Slide Feedback

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/pitches#1]
Mein (kurzes) Feedback zu den Slides
- die Slides angenehm informell
- #/4/2 und #/4/3 sind mMn zu voll; ausserdem ist die Transition unglücklich (ein Blendeffekt wäre hier besser)
- #/5/5: Die Akronyme BE, AR, DS, IM, TT und OP sind für mich nicht selbsterklärend (ggfs. einmalige Legende für offline Reader)
- #/5/5 bis #/5/12 ggfs. andere Transition dann wäre der Effekt des nach-und-nach Aufbaus nicht so gestört / nachvollziehbarer

**Comment by culmat** [comment]
Merci.

Habe fade transition konfiguriert. Die Slides #/4/2 und #/4/3  sind absichltich so voll ;-)
Lengende eingeführt in #5/5
